
name: GitHub Actions Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master  

    - name: Build
      run: |
        sudo apt update
        sudo apt install mingw-w64 -y
        sudo apt install clang -y
        ./build_windows.sh main_win.cpp -o apk_installer_Win64.exe
        /bin/bash -c g++ -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference -O3 -DNDEBUG -c /home/xingguangcuican/apk_installer/main.cpp -o ./build/Release/main.o && g++ -Wall -Wextra -Wpedantic -Wshadow -Wformat=2 -Wcast-align -Wconversion -Wsign-conversion -Wnull-dereference -O3 -DNDEBUG   ./build/Release/main.o -o ./build/Release/apk_installer_Linux 
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
          name: Upload
          path: |
            ./apk_installer_Win64.exe
            ./build/Release/apk_installer_Linux
